{{- if and $.Values.ui.enabled $.Values.ui.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $.Values.appName }}-ui
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    revision: "{{ .Release.Revision }}"
    app.kubernetes.io/name: "{{ $.Values.appName }}-ui"
    clabernetes/app: {{ $.Values.appName }}
    clabernetes/name: "{{ $.Values.appName }}-ui"
    clabernetes/component: ui
    {{- $labels := merge $.Values.globalLabels $.Values.ui.deploymentLabels }}
      {{- if $labels }}
{{ toYaml $labels | indent 4 }}
      {{- end }}
  {{- $annotations := merge $.Values.globalAnnotations $.Values.ui.deploymentAnnotations }}
  {{- if $annotations }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ui.ingress.ingressClass }}
{{ toYaml $annotations | indent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ui.ingress.ingressClass }}
  {{- if .Values.ui.ingress.tls }}
  tls:
    {{- range .Values.ui.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.ui.ingress.host }}
      http:
        paths:
          - backend:
              service:
                name: {{ .Values.appName }}-ui
                port:
                  number: 443
            path: /
            pathType: ImplementationSpecific
{{- end }}
